namespace NetEscapades.EnumGenerators;

internal static class Constants
{
    internal const string GeneratedCodeHeader = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the NetEscapades.EnumGenerators source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable
        """;
}
