name: BuildAndPack

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            6.0.x
#      - name: Force globaljson
#        run: dotnet new globaljson --sdk-version "7.0.103" --force
#      - name: Cache .nuke/temp, ~/.nuget/packages
#        uses: actions/cache@v3
#        with:
#          path: |
#            .nuke/temp
#            ~/.nuget/packages
#            !~/.nuget/packages/netescapades.enumgenerators
#            !~/.nuget/packages/netescapades.enumgenerators.attributes
#          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
#      - name: Run './build.cmd Clean Test TestPackage PushToNuGet'
#        run: ./build.cmd Clean Test TestPackage PushToNuGet
#        env:
#          GithubToken: ${{ secrets.GITHUB_TOKEN }}
#          NuGetToken: ${{ secrets.NUGET_TOKEN }}
#          MSBuildEnableWorkloadResolver: false
#      - uses: actions/upload-artifact@v1
#        with:
#          name: artifacts
#          path: artifacts
